apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: furnitureapp
  name: furnitureapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: furnitureapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: furnitureapp
    spec:
      containers:
        - image: furnitureapp
          name: furnitureapp
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /src/logs
              name: furnitureapp-claim0
      restartPolicy: Always
      volumes:
        - name: furnitureapp-claim0
          persistentVolumeClaim:
            claimName: furnitureapp-claim0
