apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: furnitureapp
  name: furnitureapp
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: furnitureapp
