apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: furnitureapp
  name: furnitureapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: furnitureapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: furnitureapp
    spec:
      containers:
        - image: furnitureapp
          name: furnitureapp
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /src/logs
              name: furnitureapp-claim0
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      restartPolicy: Always
      volumes:
        - name: furnitureapp-claim0
          persistentVolumeClaim:
            claimName: furnitureapp-claim0
