apiVersion: v1
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => plain
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "express-logs-%{+yyyy.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: logstash
  name: logstash-cm0
