apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "9999"
      port: 9999
      targetPort: 9000
  selector:
    io.kompose.service: portainer
