apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "9999"
      port: 9999
      targetPort: 9000
  selector:
    io.kompose.service: portainer
