apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redisdb
  name: redisdb
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redisdb
