apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redisdb
  name: redisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisdb
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redisdb
    spec:
      containers:
        - image: redis:latest
          name: redisdb
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
